name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout baggage-claim Repository"
        uses: actions/checkout@v3
        with:
          repository: tamu-edu-students/baggage-claim
          token: ${{ secrets.BAGGAGE_CLAIM_DEPLOY_KEY }}
          submodules: recursive

      - name: "Update submodule to referenced branch"
        run: |
          cd "plugins/dependabot-dashboard"
          git checkout ${{ github.ref }}
          git pull
          cd ../..

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
