name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Test application
        run: yarn test

      - name: Build application
        run: yarn build:all

